name: checks

on:
  push:

env:
  TERM: dumb
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  GRADLE_USER_HOME: ".github_cache_gradle/"
  TMPDIR: "/tmp"

jobs:
  verify-all-addons:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: joschi/setup-jdk@v2
        with:
          java-version: '11'
      - uses: actions/cache@v1.1.2
        with:
          path: .github_cache_gradle/
          key: verify-all-addons-gradle-v2-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}-${{ hashFiles('**/*.gradle') }}-${{ hashFiles('buildSrc/**/*.java') }}
          restore-keys: verify-all-addons-gradle-v2-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}-
      - name: verify-add-ons
        run: |
          ls -la $JAVA_HOME/bin/
          ./gradlew :addons:languages:arabic:apk:assembleRelease
